### ISSUE TITLE
Strange or wrong week number for Western

### ISSUE THREAD

**Issue by Nick-A2B** [sousyokunotomonokai/week_number#1]
Hi,
weekNumber for 29th of December 2024 (Western) is equal to 53, however when I look at US online week calendars, they all show 1. 
Looks like a bug or I don't understand what Western is used for.

**Comment by sousyokunotomonokai** [comment]
hi @Nick-A2B,
Sorry for late reply. I forgot to enable github notification.

Yes, It seems it is a bug from the view of standard specification.
It is convenient for me (for my app) to return 53 because 29th dec 2024 is 53th week of 2024.
Anyway, I'll fix it soon.

Thank you for a  bug report.

**Comment by Nick-A2B** [comment]
> hi @Nick-A2B, Sorry for late reply. I forgot to enable github notification.
> 
> Yes, It seems it is a bug from the view of standard specification. It is convenient for me (for my app) to return 53 because 29th dec 2024 is 53th week of 2024. Anyway, I'll fix it soon.
> 
> Thank you for a bug report.

Thanks for a quick fix!
